#!/bin/sh

set -e

. tools/messages.sh

status "Running unit tests ..."
ruby -I. tests/tools/*.rb
prove -lj4 tests/unit/logic/*.t

status "Copying configuration to dist directory ..."
rm -rf dist
mkdir -p dist
rsync -a redirector/. dist/.

(
    IFS=,
    read titles
    while read site domain rest_of_line
    do
        status "Check for incorrect domains ..."
        awk < data/mappings/${site}.csv -F, '$1 !~ /^"?https?:\/\/'${domain}'/' > dist/${site}_incorrect.txt
        count=$(cat dist/${site}_incorrect.txt | wc -l)

        if [ $count -gt 1 ] ; then
            warning "There are incorrect domains in data/mappings/${site}.csv - see dist/${site}_incorrect.txt"

            status "Creating a mappings_source excluding incorrect domains ..."
            head -1 data/mappings/${site}.csv >  dist/${site}_mappings_source.csv
            awk < data/mappings/${site}.csv -F, '$1 ~ /^"?https?:\/\/'${domain}'/' >> dist/${site}_mappings_source.csv
        else
            rm dist/${site}_incorrect.txt
            cp data/mappings/${site}.csv dist/${site}_mappings_source.csv
        fi

        status "Testing mappings are in a valid format ..."
        prove -l tools/validate_csv.pl :: dist/${site}_mappings_source.csv

        status "Creating mappings from $site source ..."
        perl -Ilib tools/create_mappings.pl dist/${site}_mappings_source.csv

        status "Creating 410 page for $site ... "
        #it would be better if these two files were automatically generated by the process...
        if [ ! -f dist/${domain}.location_suggested_links.conf -a ! -f dist/${domain}.location_suggested_links.conf ]; then
                touch dist/${domain}.no_suggested_links.conf
        fi
        if [ ! -f dist/${domain}.archive_links.conf ]; then
            touch dist/${domain}.archive_links.conf
        fi
        cat \
            redirector/410_preamble.php \
            dist/${domain}.*suggested_links*.conf \
            dist/${domain}.archive_links.conf \
            redirector/410_header.php \
            redirector/static/${site}/410.html \
                > dist/static/${site}/410.php
        cp redirector/410_suggested_links.php dist/static/${site}

        status "Creating sitemap for $site ..."
        perl tools/sitemap.pl dist/${site}_mappings_source.csv $domain > dist/static/${site}/sitemap.xml

        status "Testing sitemap for $site ..."
        prove tools/test_sitemap.pl :: dist/static/${site}/sitemap.xml $domain
    done
    report
) < data/sites.csv

ok "Redirector build succeeded."
