#!/bin/sh

set -e
mkdir -p dist

ANSI_RED="\033[31m"
ANSI_GREEN="\033[32m"
ANSI_YELLOW="\033[33m"
ANSI_BLUE="\033[34m"
ANSI_RESET="\033[0m"
ANSI_BOLD="\033[1m"

status () {
  echo "${ANSI_BLUE}---> ${@}${ANSI_RESET}" >&2
}

ok () {
  echo "${ANSI_GREEN}${ANSI_BOLD}OK:${ANSI_RESET} ${ANSI_GREEN}${@}${ANSI_RESET}" >&2
}

warning () {
  echo "${ANSI_YELLOW}${ANSI_BOLD}OK:${ANSI_RESET} ${ANSI_YELLOW}${@}${ANSI_RESET}" >&2
}

error () {
  echo "${ANSI_RED}${ANSI_BOLD}ERROR:${ANSI_RESET} ${ANSI_RED}${@}${ANSI_RESET}" >&2
}

status "Running unit tests..."
ruby -I. tests/tools/*.rb
prove -lj4 tests/unit/logic/*.t

status "Copying configuration to dist directory..."
rm -rf dist/*
rsync -a redirector/. dist/.
warnings=0

(
    IFS=,
    read titles
    while read site redirected old_homepage rest
    do
        status "Check for incorrect domains..."
        awk < data/mappings/${site}.csv -F, '$1 !~ /^"?https?:\/\/'${old_homepage}'/' > dist/${site}_incorrect.txt
        count=$(cat dist/${site}_incorrect.txt | wc -l)
        if [ $count -gt 1 ] ; then
            warning "WARNING===>There are incorrect domains in data/mappings/${site}.csv"
            warning "WARNING===>These have been saved in dist/${site}_incorrect.txt"
            warning "WARNING===>Config will not be generated for the invalid host names. Valid config from that file will be generated."
            warnings=`expr $warnings + 1`
            status "Creating a mappings_source that doesn't contain those domains..."
            head -1 data/mappings/${site}.csv >  dist/${site}_mappings_source.csv
            awk < data/mappings/${site}.csv -F, '$1 ~ /^"?https?:\/\/'${old_homepage}'/' >> dist/${site}_mappings_source.csv
        else
            rm dist/${site}_incorrect.txt
            cp data/mappings/${site}.csv dist/${site}_mappings_source.csv
        fi
        if [ $redirected == N ]; then
            status "Testing sources are valid for in progress site $site..."
            prove -l tests/unit/sources/${site}_valid_lines.t
        fi
        status "Creating mappings from $site source..."
        perl -Ilib create_mappings.pl dist/${site}_mappings_source.csv

        status "Creating 410 page for $site... "
        #it would be better if these two files were automatically generated by the process...
        if [ ! -f dist/${old_homepage}.location_suggested_links.conf -a ! -f dist/${old_homepage}.location_suggested_links.conf ]; then
                touch dist/${old_homepage}.no_suggested_links.conf
        fi
        if [ ! -f dist/${old_homepage}.archive_links.conf ]; then
            touch dist/${old_homepage}.archive_links.conf
        fi
        cat \
            redirector/410_preamble.php \
            dist/${old_homepage}.*suggested_links*.conf \
            dist/${old_homepage}.archive_links.conf \
            redirector/410_header.php \
            redirector/static/${site}/410.html \
                > dist/static/${site}/410.php
        cp redirector/410_suggested_links.php dist/static/${site}

        status "Creating sitemap for $site..."
        perl tools/sitemap.pl dist/${site}_mappings_source.csv $old_homepage > dist/static/${site}/sitemap.xml

        status "Testing sitemap for $site..."
        # prove bin/test_sitemap.pl :: dist/static/${site}/sitemap.xml $old_homepage 
    done
    if [ $warnings -gt 0 ]; then
        warning "WARNINGS===>There are $warnings warnings."
    fi
) < sites.csv

ok "Redirector build succeeded."
