#!/bin/bash

set -e
mkdir -p dist

echo "Running unit tests..."
prove -lj4 tests/unit/logic/*.t

echo "Copying configuration to dist directory..."
rm -rf dist/*
rsync -a redirector/. dist/.
(
    IFS=,
    read titles
    while read site redirected old_homepage rest
    do
        cp data/mappings/${site}.csv dist/${site}_mappings_source.csv
        if [ $redirected == N ]; then
            echo "Testing sources are valid for in progress site $site..."
            prove -l tests/unit/sources/${site}_valid_lines.t
        fi
        echo "Creating mappings from $site source..."
        perl -Ilib create_mappings.pl dist/${site}_mappings_source.csv

        echo "Creating 410 page for $site... "
        #it would be better if these two files were automatically generated by the process...
        if [ ! -f dist/${old_homepage}.location_suggested_links.conf -a ! -f dist/${old_homepage}.location_suggested_links.conf ]; then
                touch dist/${old_homepage}.no_suggested_links.conf
        fi
        if [ ! -f dist/${old_homepage}.archive_links.conf ]; then
            touch dist/${old_homepage}.archive_links.conf
        fi
        cat \
            redirector/410_preamble.php \
            dist/${old_homepage}.*suggested_links*.conf \
            dist/${old_homepage}.archive_links.conf \
            redirector/410_header.php \
            redirector/static/${site}/410.html \
                > dist/static/${site}/410.php
        cp redirector/410_suggested_links.php dist/static/${site}

        echo "Creating sitemap for $site..."
        perl tools/sitemap.pl dist/${site}_mappings_source.csv $old_homepage > dist/static/${site}/sitemap.xml

        echo "Testing sitemap for $site..."
        prove bin/test_sitemap.pl :: dist/static/${site}/sitemap.xml $old_homepage 
    done
) < sites.csv

echo "Redirector build succeeded."
