#
#  makefile generated for <%=site%>
#
<%=site%>_aliases=<%=[aliases].join(' ')%>

#
#  build individual site
#
<%=site%>::	dist_<%=site%>

dist_<%=site%>:	config_<%=site%> maps_<%=site%> static_<%=site%>

#
#  nginx config
#
config::	config_<%=site%>

config_<%=site%>::	\
	$(configdir)/<%=site%>.conf

ifeq ($(wildcard configs/<%=site%>.conf),)
$(configdir)/<%=site%>.conf:	$(sitesdir)/<%=site%>.yml templates/nginx.erb
	@mkdir -p $(configdir)
	$(ERB) -y $(sitesdir)/<%=site%>.yml templates/nginx.erb > $@
else
$(configdir)/<%=site%>.conf:	configs/<%=site%>.conf
	@mkdir -p $(configdir)
	cp configs/<%=site%>.conf $@
endif

#
#  nginx maps
#
maps::	maps_<%=site%>

maps_<%=site%>::	\
<% [servers].flatten.each do |host|
        next unless host %>	$(mapsdir)/<%=site%>/<%=host%>.conf \
<% end %>	$(mapsdir)/<%=site%>/<%=host%>.conf

$(mapsdir)/<%=site%>/<%=host%>.conf:	$(mappingsdir)/<%=site%>.csv tools/generate_maps.pl
	@mkdir -p $(mapsdir)/<%=site%>
	tools/generate_maps.pl --dir $(mapsdir)/<%=site%> $(mappingsdir)/<%=site%>.csv
	mv $(mapsdir)/<%=site%>/location.conf $@

<% [servers].flatten.each do |host|
        next unless host %>
$(mapsdir)/<%=site%>/<%=host%>.conf:	$(mappingsdir)/<%=site%>.csv tools/generate_locations.pl
	@mkdir -p $(mapsdir)/<%=site%>
	tools/generate_locations.pl --host <%=host%> < $(mappingsdir)/<%=site%>.csv > $@
<% end %>

#
#  static assets
#
static::	static_<%=site%>

static_<%=site%>::	\
	$(staticdir)/<%=site%>/404.php \
	$(staticdir)/<%=site%>/410.php \
	$(staticdir)/<%=site%>/418.php \
	$(staticdir)/<%=site%>/robots.txt \
	$(staticdir)/<%=site%>/sitemap.xml

$(staticdir)/<%=site%>/404.php:	$(sitesdir)/<%=site%>.yml templates/404.erb
	@mkdir -p $(staticdir)/<%=site%>
	$(ERB) -y $(sitesdir)/<%=site%>.yml templates/404.erb > $@

$(staticdir)/<%=site%>/410.php:	$(sitesdir)/<%=site%>.yml templates/410.erb
	@mkdir -p $(staticdir)/<%=site%>
	$(ERB) -y $(sitesdir)/<%=site%>.yml templates/410.erb > $@

$(staticdir)/<%=site%>/418.php:	$(sitesdir)/<%=site%>.yml templates/418.erb
	@mkdir -p $(staticdir)/<%=site%>
	$(ERB) -y $(sitesdir)/<%=site%>.yml templates/418.erb > $@

$(staticdir)/<%=site%>/robots.txt:	$(sitesdir)/<%=site%>.yml templates/robots.erb
	@mkdir -p $(staticdir)/<%=site%>
	$(ERB) -y $(sitesdir)/<%=site%>.yml templates/robots.erb > $@

$(staticdir)/<%=site%>/sitemap.xml:	$(mappingsdir)/<%=site%>.csv tools/generate_sitemap.pl
	@mkdir -p $(staticdir)/<%=site%>
	tools/generate_sitemap.pl $(mappingsdir)/<%=site%>.csv <%=host%> > $@

#
#  validate
#
validate::	validate_<%=site%> validate_<%=site%>_sitemap

validate_<%=site%>::	\
	$(validdir)/<%=site%>.valid

validate_<%=site%>_sitemap:: \
	$(validdir)/<%=site%>_sitemap.valid

$(validdir)/<%=site%>.valid:	$(mappingsdir)/<%=site%>.csv tools/validate_mappings.pl
	@rm -f $@
	@mkdir -p $(validdir)
	tools/validate_mappings.pl --whitelist "$(whitelist)" --blacklist "$(blacklist)" --hosts "<%=host%> $(<%=site%>_aliases)" <%=options%> $(mappingsdir)/<%=site%>.csv && touch $@

$(validdir)/<%=site%>_sitemap.valid:	$(staticdir)/<%=site%>/sitemap.xml tools/test_sitemap.pl
	@rm -f $@
	@mkdir -p $(validdir)
	tools/test_sitemap.pl $(staticdir)/<%=site%>/sitemap.xml <%=host%> && touch $@

#
#  clean
#
clean::	clean_<%=site%>

clean_<%=site%>:	clobber_<%=site%>
	rm -f $(validdir)/<%=site%>.valid $(validdir)/<%=site%>_sitemap.valid

#
#  clobber
#
clobber::	clobber_<%=site%>

clobber_<%=site%>:
	rm -rf $(mapsdir)/<%=site%> $(staticdir)/<%=site%> $(configdir)/<%=site%>.conf
