#!/usr/bin/env ruby

require 'csv'

CSV.new(STDIN, headers: false).each_with_index do |row, i|
  if i > 0
    row[0] = row[0].gsub(',', '%2C') if row[0]
    row[1] = row[1].gsub(',', '%2C') if row[1]
  end
  puts row.to_csv
end